# docker run -p 5000:5000 -p 5001:5001 -e ASPNETCORE_HTTP_PORT=https://+:5001 -e ASPNETCORE_URLS=http://+:5000  oichii/poll-app:1.0.0
services:
  app:
    build: .
    ports:
      - 5000:5000
      - 5001:5001
    links:
      - db
    depends_on:
      - db
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:5001
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__PostgreSQLConnection=Server=db;Port=5432;Database=poll-app-db-dev;Username=postgres;Password=password
      # - ConnectionStrings__PostgreSQLConnection=Server=db;Database=poll-app-db-dev;Username=postgres;Password=password
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: poll-app-db-dev
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data: