// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiTutorial.Data;

#nullable disable

namespace WebApiTutorial.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231128191435_ChangeVoteOption")]
    partial class ChangeVoteOption
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiTutorial.Models.Poll", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("WebApiTutorial.Models.PollOption", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("PollID")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PollID");

                    b.ToTable("PollOption");
                });

            modelBuilder.Entity("WebApiTutorial.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PollOptionID")
                        .HasColumnType("int");

                    b.HasKey("Username");

                    b.HasIndex("PollOptionID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApiTutorial.Models.PollOption", b =>
                {
                    b.HasOne("WebApiTutorial.Models.Poll", null)
                        .WithMany("Options")
                        .HasForeignKey("PollID");
                });

            modelBuilder.Entity("WebApiTutorial.Models.User", b =>
                {
                    b.HasOne("WebApiTutorial.Models.PollOption", null)
                        .WithMany("VotedUsers")
                        .HasForeignKey("PollOptionID");
                });

            modelBuilder.Entity("WebApiTutorial.Models.Poll", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("WebApiTutorial.Models.PollOption", b =>
                {
                    b.Navigation("VotedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
